### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by cristianraiber**

### CODE REVIEW

**Comment by pjrobertson** [comment]
Hi @cristianraiber , unfortunately this latest code still does not work. The dropdowns work on Desktop but not on mobile. You can see my test side with the latest code from the HEAD of your branch here:

https://test.smartairfilters.com/cn/en/

(I'm using a self signed certificate, so you can ignore the SSL warning)

**Comment by cristianraiber** [comment]
@razvanaldea89 - please see @pjrobertson answer above.

**Comment by razvanaldea89** [comment]
@pjrobertson  Could you tell me how did you test the functionality and what exactly didn't work on mobile? 
Thankyou

**Comment by pjrobertson** [comment]
I loaded test.smartairfilters.com <http://test.smartairfilters.com/> on an Android device with Chrome installed, and attempted to click the drop down buttons in the top menu (e.g the ‘About’ dropdown)

**Comment by razvanaldea89** [comment]
Thankyou for your response. I am asking because I tested with the same procedure but the menu was working. Had to look really hard for the arrows to click ( but that was because of the colors. The arrows are in the right  part of the menu  ) but it was working. Maybe you had some cache problems or something? Could you please try again ? 
Thankyou.

**Comment by pjrobertson** [comment]
Sorry I didn't get back to this sooner @razvanaldea89 

I tried clearing caches/disabling caching plugins and it's still the same. Check out the site: https://test.smartairfilters.com/cn/en/ (it's password protected, username/password both are 'smart')

**Pull request merged**
